name: CI (.NET 8)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore Chirp.sln
      - name: Build
        run: dotnet build Chirp.sln -c Release --no-restore
      - name: Test
        run: dotnet test Chirp.sln -c Release --no-build --verbosity normal
